#!/usr/bin/env bash
#Create the PID file containing the script's PID
#Displays some sentences
#Deletes the file upon recieving SIGOUT or SIGTERM

pid_file="/var/run/myscript.pid"

# Function to handle SIGTERM and SIGQUIT signals
terminate_script() {
    echo "Deleting PID file and terminating..."
    rm -f "$pid_file"
    exit 0
}

# Function to handle SIGINT signal
interrupt_signal() {
    echo "Y U no love me?!"
}

# Set signal handlers
trap 'terminate_script' SIGTERM SIGQUIT
trap 'interrupt_signal' SIGINT

# Create the PID file containing the script's PID
echo $$ > "$pid_file"

echo "To infinity and beyond!"
while true; do
    echo "To infinity and beyond!"
    sleep 1
done
