#!/usr/bin/env bash
#Create the PID file containing the script's PID
#Displays some sentences
#Deletes the file upon recieving SIGOUT or SIGTERM

pid_file="/var/run/myscript.pid"
echo $$ > "$pid_file"

terminate_script() {
    echo "I hate the kill command"
    rm -f "$pid_file"
    exit 0
}

interrupt_signal() {
    echo "Y U no love me?!"
}


while true
do
    echo "To infinity and beyond!"
    sleep 2
    trap 'interrupt_signal' SIGNET
    trap 'terminate_script' SIGTERM SIGQUIT
done
