#!/usr/bin/env bash
# a Bash script that loops from 1 to 10 
i=0
while [[ $i -lt 10 ]]; do
echo Best School
((i++))
if [[ $i -eq 3 ]]; then
echo Bad luck
elif [[ $i -eq 7 ]]; then
echo good luck
else
:
fi
done
