#!/usr/bin/env bash
# Create an SSH key pair with a passphrase
ssh-keygen -b 4096 -f school -t rsa -N betty

# Check if key generation was successful
if [ $? -eq 0 ]; then
  echo "SSH key pair generation successful!"
  echo "Private key: school"
  echo "Public key: school.pub"
else
  echo "Error: Key generation failed!"
fi

